STYLER_SCALETYPE_NONE           = 0
STYLER_SCALETYPE_FIXED          = 1
STYLER_SCALETYPE_INCREMENT      = 2
STYLER_POSITIONTYPE_NONE        = 3
STYLER_POSITIONTYPE_FIXED       = 4 
STYLER_POSITIONTYPE_INCREMENT   = 5
